# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile with Gradle
      run: ./gradlew compileJava

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test
    - uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: build/reports # or path/to/artifact

  Assemble:

    runs-on: ubuntu-latest

    outputs:
      JAR_FILENAME: ${{ steps.passJarName.outputs.JAR_FILENAME }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble with Gradle
      run: ./gradlew assemble
    - uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: build/libs
    - name: Set Jar Name to Environment Variable
      run: for entry in "build/libs"/*; do echo "JAR_FILENAME=$(echo $(basename ${entry}))" >> $GITHUB_ENV ; done
    - id: passJarName
      name: Pass Jar Name
      run: echo "::set-output name=JAR_FILENAME::$JAR_FILENAME"

  Release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    needs: Assemble
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: ${{ needs.Assemble.outputs.JAR_FILENAME }}
        path: download
    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags') }}
      with:
        files: download/${{ needs.Assemble.outputs.JAR_FILENAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
